// data_teams_world.js
// World-tier CPU teams (fixed data)
// Source: CPUチーム確定.txt（ワールドチーム）
// NOTE: ここでは「原文どおりのパッシブ説明」を raw に保持（後でエンジン側で効果に変換しやすくする）

export const TEAMS_WORLD = Object.freeze([
  {
    id: 'W01',
    tier: 'world',
    name: 'ホークス',
    strength: 95,
    tagline: '世界No.1のチーム力',
    members: ['アサモモ', 'ヨルモモ', 'ネコヤダイ'],
    passive: {
      name: '王者の完成度',
      desc: '味方全員のAim+3＆Agility+2',
      raw: '味方全員のAim+3＆Agility+2',
    },
  },
  {
    id: 'W02',
    tier: 'world',
    name: 'ブラックオーダー',
    strength: 92,
    tagline: 'ホークスのライバル',
    members: ['サノース', 'プロキシマン', 'マウマウ'],
    passive: {
      name: '黒の圧力',
      desc: '敵全体の命中率-3%',
      raw: '敵全体の命中率-3%',
    },
  },
  {
    id: 'W03',
    tier: 'world',
    name: 'フリーズマスターズ',
    strength: 90,
    tagline: '冷酷な最恐集団',
    members: ['フリーザー', 'クーラー', 'ゴールド'],
    passive: {
      name: '冷酷支配',
      desc: '敵全体のAgility-2＆回復量-10%',
      raw: '敵全体のAgility-2＆回復量-10%',
    },
  },
  {
    id: 'W04',
    tier: 'world',
    name: 'アカツキ',
    strength: 90,
    tagline: '企業財力が世界一',
    members: ['イカリーノ', 'イカススム', 'ヨジョウ'],
    passive: {
      name: '資金力',
      desc: '戦闘開始時、味方全員Armor+12 ※最大100',
      raw: '戦闘開始時、味方全員Armor+12 ※最大100',
    },
  },
  {
    id: 'W05',
    tier: 'world',
    name: 'アンドロメダ',
    strength: 90,
    tagline: 'ロボのごとく正確無比',
    members: ['ジュピター', 'ムーン', 'アースドン'],
    passive: {
      name: '機械精度',
      desc: '味方全員の命中率+4%',
      raw: '味方全員の命中率+4%',
    },
  },
  {
    id: 'W06',
    tier: 'world',
    name: '鬼ヶ島',
    strength: 90,
    tagline: '圧倒的連携力',
    members: ['カイドウロック', 'キングスキー', 'クイーンデフ'],
    passive: {
      name: '怪物連携',
      desc: '味方全員の被ダメージ-7%',
      raw: '味方全員の被ダメージ-7%',
    },
  },
  {
    id: 'W07',
    tier: 'world',
    name: '大将オールスターズ',
    strength: 89,
    tagline: '個々が強い',
    members: ['アカイノシシ', 'キヒヒ', 'アオクジャク'],
    passive: {
      name: '個の暴力',
      desc: '味方全員のダメージ+6%',
      raw: '味方全員のダメージ+6%',
    },
  },
  {
    id: 'W08',
    tier: 'world',
    name: 'ムギワラーノ',
    strength: 87,
    tagline: '主人公的チーム',
    members: ['ルーフ', 'ゾーロ', 'ダイサンジ'],
    passive: {
      name: '主人公補正',
      desc: '戦闘中1回だけ被ダメ無効 ※チームで1回',
      raw: '戦闘中1回だけ被ダメ無効 ※チームで1回',
    },
  },
  {
    id: 'W09',
    tier: 'world',
    name: 'ニンジャタイ',
    strength: 87,
    tagline: '',
    members: ['ナルトノ', 'サラスケ', 'サクランド'],
    passive: {
      name: '忍び足',
      desc: '戦闘1ターン目だけ敵の命中率-5%',
      raw: '戦闘1ターン目だけ敵の命中率-5%',
    },
  },
  {
    id: 'W10',
    tier: 'world',
    name: 'ホールケーキ',
    strength: 86,
    tagline: '',
    members: ['カタクリコ', 'クラッカー', 'オーブンレンジ'],
    passive: {
      name: '甘党強化',
      desc: '戦闘中の回復アイテム効果+15%',
      raw: '戦闘中の回復アイテム効果+15%',
    },
  },
  {
    id: 'W11',
    tier: 'world',
    name: 'スカイハイ',
    strength: 86,
    tagline: '',
    members: ['ヴァルキー', 'レヴント', 'クリップトン'],
    passive: {
      name: '高所優位',
      desc: '味方全員の弱狙い率+15%',
      raw: '味方全員の弱狙い率+15%',
    },
  },
  {
    id: 'W12',
    tier: 'world',
    name: '読みかけの本',
    strength: 88,
    tagline: '最高のパフォーマンス',
    members: ['あのヒーロー', '見習いビーム', 'いつかの巨人'],
    passive: {
      name: '物語補正',
      desc: 'HP半分以下で味方全員のAim+4',
      raw: 'HP半分以下で味方全員のAim+4',
    },
  },
  {
    id: 'W13',
    tier: 'world',
    name: 'レジェンズ',
    strength: 88,
    tagline: 'ファイト力世界一',
    members: ['レイース', 'オックタン', 'ブラハン'],
    passive: {
      name: '戦闘民族',
      desc: '味方全員のCrit率+3%',
      raw: '味方全員のCrit率+3%',
    },
  },
  {
    id: 'W14',
    tier: 'world',
    name: 'テイオウ',
    strength: 84,
    tagline: '安定感抜群',
    members: ['アカシーマ', 'アオミン', 'ムラバラ'],
    passive: {
      name: '帝王の安定',
      desc: '味方全員の被弾率-3%',
      raw: '味方全員の被弾率-3%',
    },
  },
  {
    id: 'W15',
    tier: 'world',
    name: 'ウルフキッド',
    strength: 84,
    tagline: '最速移動チーム',
    members: ['ウルフ', 'アンドル', 'エクシーズ'],
    passive: {
      name: '最速',
      desc: '味方全員のAgility+3',
      raw: '味方全員のAgility+3',
    },
  },
  {
    id: 'W16',
    tier: 'world',
    name: 'デーモンクラン',
    strength: 84,
    tagline: '悪知恵の働く強豪',
    members: ['ラプソン', 'プチソン', 'エッソン'],
    passive: {
      name: '悪知恵',
      desc: '敵1人を指定して命中率-6%',
      raw: '敵1人を指定して命中率-6%',
    },
  },
  {
    id: 'W17',
    tier: 'world',
    name: 'デビルバット',
    strength: 83,
    tagline: 'エイム重視',
    members: ['ヒルーマ', 'セナシールド', 'モンタン'],
    passive: {
      name: '狙撃精度',
      desc: '味方全員のAim+3',
      raw: '味方全員のAim+3',
    },
  },
  {
    id: 'W18',
    tier: 'world',
    name: 'ディスティニーズ',
    strength: 84,
    tagline: '',
    members: ['ミミッキー', 'ドーナルド', 'プルフート'],
    passive: {
      name: 'ドリーム連携',
      desc: '味方全員のMove+1＆Armorダメージ-3%',
      raw: '味方全員のMove+1＆Armorダメージ-3%',
    },
  },
  {
    id: 'W19',
    tier: 'world',
    name: 'ドンキホーテ',
    strength: 84,
    tagline: '',
    members: ['ドフラクック', 'ディアマール', 'ピースケ'],
    passive: {
      name: '支配者',
      desc: '敵全体のMental-5%扱い',
      raw: '敵全体のMental-5%扱い',
    },
  },
  {
    id: 'W20',
    tier: 'world',
    name: 'CP3',
    strength: 82,
    tagline: '',
    members: ['ルーチ', 'カック', 'カリーファ'],
    passive: {
      name: '諜報',
      desc: '敵の弱狙い率+10%',
      raw: '敵の弱狙い率+10%',
    },
  },
  {
    id: 'W21',
    tier: 'world',
    name: 'イレブンズ',
    strength: 81,
    tagline: '',
    members: ['カーミュ', 'レベーカ', 'セニャ'],
    passive: {
      name: 'イレブン連携',
      desc: '味方全員のAim+2＆Agility+1',
      raw: '味方全員のAim+2＆Agility+1',
    },
  },
  {
    id: 'W22',
    tier: 'world',
    name: 'レインボーロード',
    strength: 81,
    tagline: '',
    members: ['アカスター', 'アオアース', 'キンミドリ'],
    passive: {
      name: '虹加速',
      desc: '戦闘開始時、味方全員のAgility+2',
      raw: '戦闘開始時、味方全員のAgility+2',
    },
  },
  {
    id: 'W23',
    tier: 'world',
    name: 'アーティスト',
    strength: 80,
    tagline: '',
    members: ['ゴッホチー', 'ピカソウ', 'ミューシャ'],
    passive: {
      name: '芸術爆発',
      desc: '味方全員のCrit率+2%＆命中率+1%',
      raw: '味方全員のCrit率+2%＆命中率+1%',
    },
  },
  {
    id: 'W24',
    tier: 'world',
    name: 'もののけ',
    strength: 80,
    tagline: '',
    members: ['ライジングサン', 'アシタング', 'デイダラ'],
    passive: {
      name: '霊気',
      desc: '敵全体の被ダメージ+3%',
      raw: '敵全体の被ダメージ+3%',
    },
  },
  {
    id: 'W25',
    tier: 'world',
    name: 'かみかくし',
    strength: 80,
    tagline: '',
    members: ['チヒロ', 'ユーババ', 'カオアリ'],
    passive: {
      name: '神隠し',
      desc: '戦闘開始時、敵1人の行動順を最後にする確率+50%',
      raw: '戦闘開始時、敵1人の行動順を最後にする確率+50%',
    },
  },
  {
    id: 'W26',
    tier: 'world',
    name: '13階段',
    strength: 80,
    tagline: '',
    members: ['ぜムンクルス', 'マルシャー', 'サイクル'],
    passive: {
      name: '階段罠',
      desc: '戦闘中1回だけ敵の攻撃をミスにする',
      raw: '戦闘中1回だけ敵の攻撃をミスにする',
    },
  },
  {
    id: 'W27',
    tier: 'world',
    name: 'ヴィランズ',
    strength: 79,
    tagline: '',
    members: ['マレフィファント', 'ジャーファル', 'ハーデス'],
    passive: {
      name: '悪意',
      desc: '敵全体の回復量-12%',
      raw: '敵全体の回復量-12%',
    },
  },
  {
    id: 'W28',
    tier: 'world',
    name: 'グリッチハンターズ',
    strength: 79,
    tagline: '',
    members: ['バグズ', 'ノイズ', 'パッチ'],
    passive: {
      name: 'バグ侵食',
      desc: '敵全体のAim-2',
      raw: '敵全体のAim-2',
    },
  },
  {
    id: 'W29',
    tier: 'world',
    name: 'シーソルト',
    strength: 78,
    tagline: '',
    members: ['ロクス', 'シオ', 'アクリア'],
    passive: {
      name: '塩耐性',
      desc: '味方全員の被ダメージ-4%',
      raw: '味方全員の被ダメージ-4%',
    },
  },
  {
    id: 'W30',
    tier: 'world',
    name: 'ハイパーカーニバル',
    strength: 78,
    tagline: '',
    members: ['ピエロック', 'ショーマン', 'ドラムン'],
    passive: {
      name: '盛り上げ',
      desc: '戦闘中、味方全員のMental+5%扱い',
      raw: '戦闘中、味方全員のMental+5%扱い',
    },
  },
  {
    id: 'W31',
    tier: 'world',
    name: 'テンテン',
    strength: 77,
    tagline: '',
    members: ['フーラ', 'マーユ', 'ヒューガ'],
    passive: {
      name: '点取り',
      desc: '敵が倒れるたび味方全員のAim+1 ※最大+3',
      raw: '敵が倒れるたび味方全員のAim+1 ※最大+3',
    },
  },
  {
    id: 'W32',
    tier: 'world',
    name: 'プリンセス',
    strength: 77,
    tagline: '',
    members: ['シンディララ', 'シラユキ', 'オーロラ'],
    passive: {
      name: '姫の加護',
      desc: '戦闘中1回だけHPが0になった時HP1で耐える ※チームで1回',
      raw: '戦闘中1回だけHPが0になった時HP1で耐える ※チームで1回',
    },
  },
  {
    id: 'W33',
    tier: 'world',
    name: 'ナイトメア',
    strength: 77,
    tagline: '',
    members: ['ドレッド', 'ファントム', 'スリープ'],
    passive: {
      name: '悪夢',
      desc: '敵全体のAgility-1＆命中率-1%',
      raw: '敵全体のAgility-1＆命中率-1%',
    },
  },
  {
    id: 'W34',
    tier: 'world',
    name: 'オーケストラ',
    strength: 76,
    tagline: '',
    members: ['ピッコロ', 'チェロ', 'パイプ'],
    passive: {
      name: '合奏',
      desc: '味方全員のAim+1＆Agility+1',
      raw: '味方全員のAim+1＆Agility+1',
    },
  },
  {
    id: 'W35',
    tier: 'world',
    name: 'ネオンパルス',
    strength: 75,
    tagline: '',
    members: ['グロウ', 'フラッシュ', 'ビート'],
    passive: {
      name: 'ネオン加速',
      desc: '戦闘1ターン目だけ味方全員のAgility+4',
      raw: '戦闘1ターン目だけ味方全員のAgility+4',
    },
  },
  {
    id: 'W36',
    tier: 'world',
    name: 'クロノギア',
    strength: 73,
    tagline: '',
    members: ['タイム', 'ギアード', 'リセット'],
    passive: {
      name: '時間操作',
      desc: '敵1人の行動を1回遅らせる確率+25%',
      raw: '敵1人の行動を1回遅らせる確率+25%',
    },
  },
  {
    id: 'W37',
    tier: 'world',
    name: 'メテオラッシ',
    strength: 71,
    tagline: '',
    members: ['メテオ', 'ノヴァ', 'スターロロ'],
    passive: {
      name: '隕石圧',
      desc: '敵全体のArmor-5で開始',
      raw: '敵全体のArmor-5で開始',
    },
  },
  {
    id: 'W38',
    tier: 'world',
    name: 'ラグーンレジェンド',
    strength: 71,
    tagline: '',
    members: ['ラグーナ', 'コーラル', 'シード'],
    passive: {
      name: '海底回復',
      desc: '毎ターン味方全員Armor+2 ※最大100',
      raw: '毎ターン味方全員Armor+2 ※最大100',
    },
  },
  {
    id: 'W39',
    tier: 'world',
    name: 'ストームコア',
    strength: 70,
    tagline: '',
    members: ['サンダー', 'タイフーン', '活火山'],
    passive: {
      name: '嵐',
      desc: '戦闘開始時、敵全体の命中率-2%',
      raw: '戦闘開始時、敵全体の命中率-2%',
    },
  },
  {
    id: 'W40',
    tier: 'world',
    name: 'マジシャンズ',
    strength: 85,
    tagline: '何をするか分からない恐ろしさ',
    members: ['カオスブラック', 'イリュージョニスト', 'サクリファイス'],
    passive: {
      name: '幻惑',
      desc: '戦闘開始時、敵の弱狙い率を0%にする',
      raw: '戦闘開始時、敵の弱狙い率を0%にする',
    },
  },
]);

export function getWorldTeamById(id) {
  return TEAMS_WORLD.find((t) => t.id === id) || null;
}

export function listWorldTeamsSortedByStrengthDesc() {
  return [...TEAMS_WORLD].sort((a, b) => (b.strength - a.strength) || a.name.localeCompare(b.name, 'ja'));
}
